### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by f1yegor** [arangodb-foxx/grafana-connector#6]
I'm trying to understand how to use this plugin, 

I was able to create one query for one collection with one aggregation 

![image](https://user-images.githubusercontent.com/1815205/98842194-7fc8a300-2449-11eb-892e-442aa7e12c61.png)

![image](https://user-images.githubusercontent.com/1815205/98842460-ec43a200-2449-11eb-807f-fb700e9a6a86.png)

but I don't understand how to have several aggregations or query different collections.

Probably it could be done via `templateVariables`
`templateVariables (default: empty): A JSON object that describes the values for template variables. In Grafana create a Query named QUERY (in Query Options). For each such query, create a key QUERY and an AQL as value. For example, { "size": "FOR doc IN sizes RETURN DISTINCT doc.name" }
`

, but I don't see that I have such option in grafana (v7.3.1)

Some example will be helpful.

**Comment by f1yegor** [comment]
@fceller @pluma do you need additional information?

**Comment by fceller** [comment]
@f1yegor we have updated the examples and adjusted them to version 3.
