### ISSUE TITLE
Help for usage examples for creating multiple targets in one  grafana-connector service.

### ISSUE THREAD

**Issue by yh201811** [arangodb-foxx/grafana-connector#7]
I'm trying to use grafana-connector to implement map-track panel in grafana with data from arangodb.

**Here, I need tree attribute: Time, Latitude, Longitude for each point.**

**However, I encountered several problems when using grafana-connector and hope to get examples for creating multiple targets in one grafana-connector service.**

1 I can only create one metric (target in grafana-connector setting page) for one grafana-connector service, and the format of query response json is fixed to an array of [Time, value]. It means that, since I can only set one data source service for one panel, and only one metric can be created for one data source service, I can neither get a response of an array of [Time, Latitude, Longitude] for one query nor get two responses of arrays of [Time, Latitude] and [Time, Longitude] for two queries in one panel. Please refer to the orange rectangle in PICTURE 1. 

2 I have also tried "templateVariables" and "multiValueTemplateVariables" below. For the "templateVariables", I have successfully created them in grafana variables (Please refer to PICTURE 2), however, I still failed to set the "multiValueTemplateVariables" in grafana-connector setting page to get multiple responses for multiple runs for "multiValueTemplateVariables" as what has been described below.

  - multiValueTemplateVariables (default: empty): A comma-separated list of template variables that should be treated as multi-target variables. For example, if you have a Grafana variable 'size' which contains 'small' and 'big', then two runs will be done for the above expressions. The first one will set 'grafana.size' to 'small' and the second to 'big'.
  - templateVariables (default: empty): A JSON object that describes the values for template variables. In Grafana create a Query named QUERY (in Query Options). For each such query, create a key QUERY and an AQL as value. For example, { "size": "FOR doc IN sizes RETURN DISTINCT doc.name" }.

@fceller @pluma 
**So, could you help for these problems? or provided examples for creating multiple targets in one grafana-connector service?**

Thank you so much!

[PICTURE 1]
![Presentation1](https://user-images.githubusercontent.com/84004315/128967344-d25ccb8f-ae8a-4916-8413-2c5951450321.jpg)

[PICTURE 2]
![Presentation1](https://user-images.githubusercontent.com/84004315/128967354-21d72626-20a9-4ca2-afc5-ab84c6e2db26.jpg)

**Comment by fceller** [comment]
Hi @yh201811 , we have updated the examples to version 3.

**Comment by youyounyh** [comment]
@fceller Thanks a lot.
